/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Airline;

import Airline.AirlineCompany;
import Business.AirlineBusiness;
import Faculty.FacultyProfile;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author martta
 */
public class ManageFacultyJPanel extends javax.swing.JPanel {
    JPanel mainWorkArea;
    AirlineBusiness ab;
    AirlineCompany ac;
    /**
     * Creates new form ManageFacultyJPanel
     */
    public ManageFacultyJPanel(AirlineBusiness ab,JPanel mainWorkArea,AirlineCompany ac) {
        initComponents();
        this.ab = ab;
        this.mainWorkArea = mainWorkArea;  
        this.ac = ac;
        
        populateTable();
    }
    
    public void populateTable() {
        List<FacultyProfile> facultyList = ac.getFacultyDirectory().getAllFaculty(); // get current login company

        DefaultTableModel model = (DefaultTableModel) tblFaculty.getModel();
        model.setRowCount(0);

        for (FacultyProfile faculty : facultyList) {
            Object[] row = new Object[4];
            row[0] = faculty.getId();
            row[1] = faculty.getName();
            row[2] = ac.getName(); 
            row[3] = faculty.getRole();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMngFaculty = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFaculty = new javax.swing.JTable();
        btnAddNewFaculty = new javax.swing.JButton();
        btnUpdateFaculty = new javax.swing.JButton();
        btnDeleteFaculty = new javax.swing.JButton();

        lblMngFaculty.setText("Manage Faculty");

        tblFaculty.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Name", "Company", "Role"
            }
        ));
        jScrollPane1.setViewportView(tblFaculty);

        btnAddNewFaculty.setText("Add New faculty");
        btnAddNewFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewFacultyActionPerformed(evt);
            }
        });

        btnUpdateFaculty.setText("Update Faculty");
        btnUpdateFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateFacultyActionPerformed(evt);
            }
        });

        btnDeleteFaculty.setText("Delete Faculty");
        btnDeleteFaculty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteFacultyActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(lblMngFaculty)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(399, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnDeleteFaculty)
                    .addComponent(btnUpdateFaculty)
                    .addComponent(btnAddNewFaculty))
                .addGap(118, 118, 118))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(14, 14, 14)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(294, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(lblMngFaculty)
                .addGap(67, 67, 67)
                .addComponent(btnAddNewFaculty)
                .addGap(18, 18, 18)
                .addComponent(btnUpdateFaculty)
                .addGap(18, 18, 18)
                .addComponent(btnDeleteFaculty)
                .addContainerGap(208, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(136, 136, 136)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(137, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddNewFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewFacultyActionPerformed
        // TODO add your handling code here:
        AddNewFacultyJPanel afjp = new AddNewFacultyJPanel(ac,mainWorkArea);
        mainWorkArea.add("AddNewFacultyJPanel",afjp);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
    }//GEN-LAST:event_btnAddNewFacultyActionPerformed

    private void btnUpdateFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateFacultyActionPerformed
        // TODO add your handling code here:
        UpdateFacultyJPanel ufjp = new UpdateFacultyJPanel(ac,mainWorkArea);
        mainWorkArea.add("UpdateFacultyJPanel",ufjp);
        CardLayout layout = (CardLayout) mainWorkArea.getLayout();
        layout.next(mainWorkArea);
        
    }//GEN-LAST:event_btnUpdateFacultyActionPerformed

    private void btnDeleteFacultyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteFacultyActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblFaculty.getSelectedRow();
        if (selectedRow >= 0) {
            String id = (String) tblFaculty.getValueAt(selectedRow, 0);

            boolean isDeleted = ac.getFacultyDirectory().deleteFacultyById(id);

            if (isDeleted) {
                JOptionPane.showMessageDialog(this, "Faculty deleted successfully!");
                populateTable(); 
            } else {
                JOptionPane.showMessageDialog(this, "Failed to delete faculty.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Please select a faculty to delete.", "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnDeleteFacultyActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewFaculty;
    private javax.swing.JButton btnDeleteFaculty;
    private javax.swing.JButton btnUpdateFaculty;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblMngFaculty;
    private javax.swing.JTable tblFaculty;
    // End of variables declaration//GEN-END:variables
}
