/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Faculty;

import Business.AirlineBusiness;
import Faculty.FacultyFlightAssignment;
import Faculty.FacultyProfile;
import Flight.Flight;
import java.time.format.DateTimeFormatter;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author martta
 */
public class ViewMyFlightJPanel extends javax.swing.JPanel {
    JPanel mainWorkArea;
    AirlineBusiness ab;
    FacultyProfile fp;
    /**
     * Creates new form ViewMyFlightJPanel
     */
    public ViewMyFlightJPanel(AirlineBusiness ab,JPanel mainWorkArea,FacultyProfile fp) {
        initComponents();
        this.ab = ab;
        this.mainWorkArea = mainWorkArea;   
        this.fp = fp;
        
        populateTable();
    }
    
    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) tblFlights.getModel();
        model.setRowCount(0); 


        List<FacultyFlightAssignment> assignments = ab.getffaDirectory().getAssignmentsByFacultyId(fp.getId());

        for (FacultyFlightAssignment assignment : assignments) {
            Flight flight = assignment.getFlight();
            Object[] row = new Object[5]; 
            row[0] = flight.getDepartureTime().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));
            row[1] = flight.getArrivalTime().format(DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm"));
            row[2] = flight.getDepartureStation().getCityName();
            row[3] = flight.getArrivalStation().getCityName();
            row[4] = flight.getDepartureTime().toLocalDate(); 

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlights = new javax.swing.JTable();
        lblViewMyFlight = new javax.swing.JLabel();

        tblFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Departure Time", "Arrival Time", "Departure Airport", "Destination", "Date"
            }
        ));
        jScrollPane1.setViewportView(tblFlights);

        lblViewMyFlight.setText("View My Flight");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblViewMyFlight))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(lblViewMyFlight)
                .addGap(38, 38, 38)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(129, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblViewMyFlight;
    private javax.swing.JTable tblFlights;
    // End of variables declaration//GEN-END:variables
}
