/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Admin;

import Business.AirlineBusiness;
import Flight.Flight;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author martta
 */
public class ViewFlightScheduleJPanel extends javax.swing.JPanel {
    JPanel mainWorkArea;
    AirlineBusiness ab;
    /**
     * Creates new form ViewFlightScheduleJPanel
     */
    public ViewFlightScheduleJPanel(AirlineBusiness ab,JPanel mainWorkArea) {
        initComponents();
        this.ab = ab;
        this.mainWorkArea = mainWorkArea;
        populateTable();
    }
    
    public void populateTable() {
        List<Flight> flightList = ab.getFlightDirectory().getFlights(); 

        DefaultTableModel model = (DefaultTableModel) tblFlightSchedule.getModel();
        model.setRowCount(0);

        for (Flight flight : flightList) {
            Object[] row = new Object[6]; 
            row[0] = flight.getFlightNumber();
            row[1] = flight.getAirlineCompany().getName();
            row[2] = flight.getDepartureStation().getCityName(); 
            row[3] = flight.getArrivalStation().getCityName(); 
            row[4] = flight.getDepartureTime().toString();
            row[5] = flight.getArrivalTime().toString(); 

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlightSchedule = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(242, 249, 255));

        tblFlightSchedule.setFont(new java.awt.Font("Amazon Ember", 0, 14)); // NOI18N
        tblFlightSchedule.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Flight No.", "Airline Co.", "Departure Airport", "Destination", "Departure Time", "Arrival Time"
            }
        ));
        jScrollPane1.setViewportView(tblFlightSchedule);

        jLabel1.setFont(new java.awt.Font("Amazon Ember", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 204, 255));
        jLabel1.setText("View Flight Schedule");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jLabel1)
                .addGap(65, 65, 65)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblFlightSchedule;
    // End of variables declaration//GEN-END:variables
}
