/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Admin;

import Business.AirlineBusiness;
import Order.Order;
import Ticket.Ticket;
import java.util.List;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author martta
 */
public class ViewAllTicketsJPanel extends javax.swing.JPanel {
    JPanel mainWorkArea;
    AirlineBusiness ab;
    /**
     * Creates new form ViewAllTicketsJPanel
     */
    public ViewAllTicketsJPanel(AirlineBusiness ab,JPanel mainWorkArea) {
        initComponents();
        this.ab = ab;
        this.mainWorkArea = mainWorkArea;
        populateTable();
    }
    
    
    
    public void populateTable() {
        List<Ticket> ticketList = ab.getTicketDirectory().getAllTickets();
        List<Order> orders = ab.getOrderDirectory().getAllOrders();

        //System.out.println("Ticket count: " + ticketList.size()); // 
        //System.out.println("Order count: " + orders.size()); // 

        DefaultTableModel model = (DefaultTableModel) tblTickets.getModel();
        model.setRowCount(0);

        for (Ticket ticket : ticketList) {
            String passengerName = "Not found";
            for (Order order : orders) {
                if (order.getTickets().contains(ticket)) {
                    passengerName = order.getPassenger().getName();
                    break;
                }
            }

            //System.out.println("Adding row: " + ticket.getTicketId() + " " + passengerName);

            Object[] row = {
                ticket.getFlight().getFlightNumber(),
                passengerName,
                ticket.getTicketId(),
                ticket.getCabinClass().toString(),
                ticket.getStatus().toString()
            };

            model.addRow(row);
        }

        //System.out.println("Rows in table after populate: " + model.getRowCount()); 
    }




    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewFlightSchedule = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTickets = new javax.swing.JTable();

        lblViewFlightSchedule.setText("View All Tickets");

        tblTickets.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Flight No.", "Passenger Name", "Ticket No.", "Cabin Class", "Reservation Status"
            }
        ));
        jScrollPane1.setViewportView(tblTickets);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(264, 264, 264)
                .addComponent(lblViewFlightSchedule)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 616, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(lblViewFlightSchedule)
                .addGap(53, 53, 53)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(126, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblViewFlightSchedule;
    private javax.swing.JTable tblTickets;
    // End of variables declaration//GEN-END:variables
}
