/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package UI.Passenger;

import Business.AirlineBusiness;
import Passenger.PassengerProfile;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Jiaen
 */
public class ViewOrderJPanel extends javax.swing.JPanel {
    JPanel mainWorkArea;
    AirlineBusiness ab;
    PassengerProfile pp;
    
    /**
     * Creates new form ViewOrderJPanel
     */
    public ViewOrderJPanel(AirlineBusiness ab,JPanel mainWorkArea,PassengerProfile pp) {
        initComponents();
        this.ab = ab;
        this.mainWorkArea = mainWorkArea;
        this.pp = pp;
        
        populateOrdersTable();
    }
    

    
    private void populateOrdersTable() {
        DefaultTableModel model = (DefaultTableModel) tblFlights.getModel();
        model.setRowCount(0); // Clear the table

        // Iterate over each order of the logged-in passenger
        pp.getOrders().forEach(order -> {
            order.getTickets().forEach(ticket -> {
                Object[] row = new Object[] {
                    ticket.getFlight().getFlightNumber(),
                    ticket.getFlight().getDepartureStation().getCityName(),
                    ticket.getFlight().getArrivalStation().getCityName(),
                    ticket.getFlight().getDepartureTime().toString(),
                    ticket.getFlight().getArrivalTime().toString(),
                    ticket.getFlight().getAirlineCompany().getName(),
                    ticket.getCabinClass().toString(),
                    String.format("%.2f", ticket.getPrice())
                };
                model.addRow(row);
            });
        });
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblViewLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblFlights = new javax.swing.JTable();

        lblViewLabel.setText("View My Orders");

        tblFlights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Flight No.", "Departure", "Destination", "Departure Time", "Arrival Time", "Airline", "Class", "Price Paid"
            }
        ));
        jScrollPane1.setViewportView(tblFlights);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(lblViewLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(lblViewLabel)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(285, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblViewLabel;
    private javax.swing.JTable tblFlights;
    // End of variables declaration//GEN-END:variables
}
